#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/89-tlwg-waree-synthetic.conf 0.6.3-1~ fonts-tlwg-waree -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.d/89-tlwg-waree-synthetic.conf 0.6.3-1~ fonts-tlwg-waree -- "$@"
# End automatically added section
