#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p xdiagnose -V 3.2-
fi

# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/failsafe-x" ]; then
		update-rc.d failsafe-x defaults >/dev/null || exit $?
	fi
fi
# End automatically added section
